"""add invites table

Revision ID: 22f1f6e45820
Revises: 28f5fab010fe
Create Date: 2026-08-09 11:02:32.188258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '22f1f6e45820'
down_revision = '28f5fab010fe'
branch_labels = None
depends_on = None

# Used for the explicit, manual create/drop below.
invite_role_enum = postgresql.ENUM('admin', 'author', name='invite_role')

# Used on the column itself — create_type=False stops create_table/drop_table
# from trying to manage the type's lifecycle a second time, since we're
# doing that ourselves via invite_role_enum above.
invite_role_column_type = postgresql.ENUM(
    'admin', 'author', name='invite_role', create_type=False
)


def upgrade():
    bind = op.get_bind()
    invite_role_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('role', invite_role_column_type, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], name=op.f('fk_invites_created_by_id_users')),
    sa.ForeignKeyConstraint(['used_by_id'], ['users.user_id'], name=op.f('fk_invites_used_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('code', name=op.f('uq_invites_code'))
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index('idx_invites_code', ['code'], unique=False)
        batch_op.create_index('idx_invites_created_by_id', ['created_by_id'], unique=False)
        batch_op.create_index('idx_invites_used_by_id', ['used_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index('idx_invites_used_by_id')
        batch_op.drop_index('idx_invites_created_by_id')
        batch_op.drop_index('idx_invites_code')

    op.drop_table('invites')
    # ### end Alembic commands ###

    # Drop the type manually, since create_type=False on the column meant
    # drop_table didn't touch it either.
    bind = op.get_bind()
    invite_role_enum.drop(bind, checkfirst=True)