"""add status and rejection_reason to articles

Revision ID: 28f5fab010fe
Revises: d11a95c7bbfc
Create Date: 2026-08-06 13:52:54.551064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '28f5fab010fe'
down_revision = 'd11a95c7bbfc'
branch_labels = None
depends_on = None

# Defined once, reused in both upgrade() and downgrade()
article_status_enum = postgresql.ENUM(
    'PENDING', 'PUBLISHED', 'REJECTED', name='article_status'
)


def upgrade():
    # Postgres enums are real types — they must exist before any column
    # can reference them. checkfirst=True makes this safe to rerun.
    bind = op.get_bind()
    article_status_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                article_status_enum,
                nullable=False,
                server_default='PENDING',  # required: table already has rows
            )
        )
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

    # Backfill: everything that existed before this migration was already
    # publicly visible (no status filtering existed yet), so treat it as
    # published rather than sending it all back through moderation.
    articles = table('articles', column('status'))
    op.execute(articles.update().values(status='PUBLISHED'))

    # Drop the server-side default now that backfill is done — new articles
    # should get "PENDING" from the SQLAlchemy model's default=, not silently
    # from the database.
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('status')
    # ### end Alembic commands ###

    # Drop the type too, so downgrade actually undoes everything upgrade did
    bind = op.get_bind()
    article_status_enum.drop(bind, checkfirst=True)