"""Add external_id to leagues, teams, matches

Revision ID: 647389df7047
Revises: dda641bebd2a
Create Date: 2026-08-02 10:18:06.372046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '647389df7047'
down_revision = 'dda641bebd2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_leagues_external_id'), ['external_id'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_matches_external_id'), ['external_id'])

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'author', 'user', name='user_roles'),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_teams_external_id'), ['external_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_teams_external_id'), type_='unique')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('admin', 'author', 'user', name='user_roles'),
               existing_nullable=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_matches_external_id'), type_='unique')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_leagues_external_id'), type_='unique')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
