"""Add external_url, source_name to articles, make author_id nullable

Revision ID: d6e4c69e3f58
Revises: e54264960145
Create Date: 2026-08-02 23:29:29.661862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e4c69e3f58'
down_revision = 'e54264960145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('source_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_articles_external_url'), ['external_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_articles_external_url'), type_='unique')
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('source_name')
        batch_op.drop_column('external_url')

    # ### end Alembic commands ###
