"""Add upvotes to reactions

Revision ID: dda641bebd2a
Revises: a6ac62301ebe
Create Date: 2026-08-01 13:31:47.359108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda641bebd2a'
down_revision = 'a6ac62301ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_blocklist'))
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('idx_articles_author_id', ['author_id'], unique=False)
        batch_op.create_index('idx_articles_category_id', ['category_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_article_id', ['article_id'], unique=False)
        batch_op.create_index('idx_comments_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('idx_follows_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_follows_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('idx_matches_away_team_id', ['away_team_id'], unique=False)
        batch_op.create_index('idx_matches_home_team_id', ['home_team_id'], unique=False)
        batch_op.create_index('idx_matches_league_id', ['league_id'], unique=False)

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('idx_predictions_match_id', ['match_id'], unique=False)
        batch_op.create_index('idx_predictions_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index('idx_profile_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=False))
        batch_op.create_index('idx_reactions_article_id', ['article_id'], unique=False)
        batch_op.create_index('idx_reactions_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index('idx_teams_league_id', ['league_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index('idx_teams_league_id')

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index('idx_reactions_user_id')
        batch_op.drop_index('idx_reactions_article_id')
        batch_op.drop_column('upvotes')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_index('idx_profile_user_id')
        batch_op.alter_column('gender',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('idx_predictions_user_id')
        batch_op.drop_index('idx_predictions_match_id')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('idx_matches_league_id')
        batch_op.drop_index('idx_matches_home_team_id')
        batch_op.drop_index('idx_matches_away_team_id')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('idx_follows_user_id')
        batch_op.drop_index('idx_follows_category_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comments_user_id')
        batch_op.drop_index('idx_comments_article_id')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('idx_articles_category_id')
        batch_op.drop_index('idx_articles_author_id')

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
