"""Add bookmarks table

Revision ID: e54264960145
Revises: 647389df7047
Create Date: 2026-08-02 16:27:50.748605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54264960145'
down_revision = '647389df7047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], name=op.f('fk_bookmarks_article_id_articles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_bookmarks_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'article_id', name=op.f('pk_bookmarks'))
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index('idx_bookmarks_article_id', ['article_id'], unique=False)
        batch_op.create_index('idx_bookmarks_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index('idx_bookmarks_user_id')
        batch_op.drop_index('idx_bookmarks_article_id')

    op.drop_table('bookmarks')
    # ### end Alembic commands ###
